version: "3"

services:
  mysql-authentication-db:
    image: mysql:5.6
    container_name: mysql-authentication-db
    expose: [ 3306 ]
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "test-authentication"
  mysql-backoffice-db:
    image: mysql:5.6
    container_name: mysql-backoffice-db
    expose: [ 3306 ]
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "test-backoffice"
  mysql-booking-db:
    image: mysql:5.6
    container_name: mysql-booking-db
    expose: [ 3306 ]
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "test-booking"
  mongo-db:
    container_name: workffice-mongo-db
    image: mongo:4.2.16-rc0-bionic
    environment:
      ME_CONFIG_MONGODB_SERVER: "test-workffice"
    expose: [ 27017 ]
    ports:
      - 27017:27017
