version: "3"
services:
  workffice-be:
    scale: 2
    image: nicolasnunez96/workffice-be:main
    expose: [ 8080 ]
    ports:
      - 8080:8080
    depends_on:
      - mysql-authentication-db
      - mysql-backoffice-db
      - mysql-booking-db
    environment:
      DB_BACKOFFICE_HOST: "jdbc:mysql://mysql-backoffice-db/workffice"
      DB_BACKOFFICE_USERNAME: "root"
      DB_AUTHENTICATION_HOST: "jdbc:mysql://mysql-authentication-db/workffice"
      DB_AUTHENTICATION_USERNAME: "root"
      DB_BOOKING_HOST: "jdbc:mysql://mysql-booking-db/workffice"
      DB_BOOKING_USERNAME: "root"
    env_file:
      - .env-prod
  mysql-authentication-db:
    image: mysql:5.6
    container_name: mysql-authentication-db
    ports: [ 3306 ]
    environment:
      MYSQL_DATABASE: "workffice"
    env_file:
      - .env-prod
    volumes:
      - mysql-authentication-db:/var/lib/mysql
  mysql-backoffice-db:
    image: mysql:5.6
    container_name: mysql-backoffice-db
    ports: [ 3306 ]
    environment:
      MYSQL_DATABASE: "workffice"
    env_file:
      - .env-prod
    volumes:
      - mysql-backoffice-db:/var/lib/mysql
  mysql-booking-db:
    image: mysql:5.6
    container_name: mysql-booking-db
    ports: [ 3306 ]
    environment:
      MYSQL_DATABASE: "workffice"
    env_file:
      - .env-prod
    volumes:
      - mysql-booking-db:/var/lib/mysql

volumes:
  mysql-booking-db:
  mysql-backoffice-db:
  mysql-authentication-db:
