FROM openjdk:11

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

WORKDIR /workffice-server

COPY ./build/libs/*.jar app.jar

CMD ["java", "-jar", "app.jar", "--spring.config.location=classpath:/prod_application.properties"]
